# 1) Create an 1D array with size=12, using
* a. np.arange   
* b. np.array   

In [2]:
import numpy as np
#a) using np.arange
arr = np.arange(1,13,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
#b) using np.array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 2)using the same elements create arrays with shape (3,4) , (3,4,1 ), (4,3,1),(4,1,3),(2,6)
* create them using  
   a. use brackets syntax(general way of creating)  
   b. use reshape method

* get the size, shape, dimensions of the above


# a.using general method 

In [31]:
#a using bracket method 
#(3,4)
arr_1 = np.array([
                  [1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]
                ])
print(arr_1)
print(arr_1.size)
print(arr_1.shape)
print(arr_1.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
(3, 4)
2


In [32]:
#(3,4,1)
arr_2 = np.array([
               [[ 1],
                [ 2],
                [ 3],
                [ 4]],

               [[ 5],
                [ 6],
                [ 7],
                [ 8]],

              [[ 9],
               [10],
               [11],
               [12]]
])
print(arr_2)
print(arr_2.size)
print(arr_2.shape)
print(arr_2.ndim)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]
12
(3, 4, 1)
3


In [33]:
#(4,3,1)
arr_3 = np.array([
 [[ 1],
  [ 2],
  [ 3]],

 [[ 4],
  [ 5],
  [ 6]],

 [[ 7],
  [ 8],
  [ 9]],

 [[10],
  [11],
  [12]]])
print(arr_3)
print(arr_3.size)
print(arr_3.shape)
print(arr_3.ndim)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]
12
(4, 3, 1)
3


In [34]:
#(4,1,3)
arr_4 = np.array([
               [[1,2,3]],
               [[4,5,6]],
               [[7,8,9]],
               [[10,11,12]]])
print(arr_4)
print(arr_4.size)
print(arr_4.shape)
print(arr_4.ndim)

[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]
12
(4, 1, 3)
3


In [35]:
#(2,6)
arr_5 = np.array([[1,2,3,4,5,6],
                  [7,8,9,10,11,12]])
print(arr_5)
print(arr_5.size)
print(arr_5.shape)
print(arr_5.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
12
(2, 6)
2


# b)using reshape() method

In [36]:
a = arr.reshape(3,4)
print(a)
print(a.size)
print(a.shape)
print(a.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
(3, 4)
2


In [37]:
b = arr.reshape(3,4,1)
print(b)
print(b.size)
print(b.shape)
print(b.ndim)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]
12
(3, 4, 1)
3


In [38]:
c = arr.reshape(4,3,1)
print(c)
print(c.size)
print(c.shape)
print(c.ndim)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]
12
(4, 3, 1)
3


In [39]:
d = arr.reshape(4,1,3)
print(d)
print(d.size)
print(d.shape)
print(d.ndim)

[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]
12
(4, 1, 3)
3


In [40]:
e = arr.reshape(2,6)
print(e)
print(e.size)
print(e.shape)
print(e.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
12
(2, 6)
2


# 3)create full array shape (9*9) with element 9 ,zero arrays shape (2,3,4), ones array shape (4,3,2)
    a. using general syntax  
    b. using respective functions( like full,zero,ones)

In [46]:
#full array shape (9*9) with element 9 
#a.using general syntax
arr = np.array([
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9]
               ])
print(arr)

[[9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]]


In [44]:
#using full func
np.full((9,9),9)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [50]:
#zero arrays shape (2,3,4)
arr = np.array([
                [[0,0,0,0],
                 [0,0,0,0],
                 [0,0,0,0]],
                [[0,0,0,0],
                 [0,0,0,0],
                 [0,0,0,0]]
            ])
print(arr)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [49]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [52]:
#ones array shape (4,3,2)
arr = np.array([
                [[1,1],
                 [1,1],
                 [1,1]],
                [[1,1],
                 [1,1],
                 [1,1]],
                [[1,1],
                 [1,1],
                 [1,1]],
                [[1,1],
                 [1,1],
                 [1,1]]
 ])
print(arr)


[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [51]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

# 4)using your own examples try showing the Difference between
   a. range, arange   
   b. linspace,arange  
   c. eye matrix, identity matrix

In [ ]:
#a)in the range we can give only int as the step size where as in arange() we can give float data type 

In [57]:
#range
a=np.array(range(1,12,3))
print(a)

[ 1  4  7 10]


In [1]:
'''a=np.array(range(1,12,3.0))
print(a)'''#uncomment for error  #it is not possible to use float datatype in these

'a=np.array(range(1,12,3.0))\nprint(a)'

In [59]:
a=np.arange(1,12,3)
print(a)

[ 1  4  7 10]


In [60]:
a=np.arange(1,12,3.0)
print(a)

[ 1.  4.  7. 10.]


In [ ]:
#b. linspace,arange
#linspace(syntax) --->(start,end,no.ofelements)
#arange(syntax) --->(start,end,step)
'''in both linspace and arange we give three arguments first and second are start and end in both 
where as the third argument in linspace is no.of elements and in arange the third argument is step'''


In [61]:
np.linspace(1,12,5)

array([ 1.  ,  3.75,  6.5 ,  9.25, 12.  ])

In [62]:
np.arange(1,12,5)

array([ 1,  6, 11])

In [ ]:
#eyematrix&identitymatrix-
'''eye returns a 2-D array with ones on the diagonal and zeros elsewhere. The main difference is that with the numpy. 
eye() the diagonal can may be offset, whereas numpy. identity() only fills the main diagonal.'''


In [63]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])